library(datapasta)
library("tidyr")
library(rstudioapi)
library(A3)
library("abc")
library(naniar)
library(visdat)
library(dplyr)
library(switchr)
library("rtimicropem")
library(notARealPackage)
require("packagemetrics")
#library("dejaVu")
p_load(xml2, jsonlite)
p_load("devtools")
#library(Rborist)
#library(rrtools)
#library(kpmt)
#library(fasjem)

require(packup)

doc <- rstudioapi::getActiveDocumentContext()$contents
depl_check_run()
